<?php

namespace App\Models;

use App\Enums\EntityStatus;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Product extends Model implements HasMedia
{
    use HasFactory, SoftDeletes, InteractsWithMedia;

    protected $fillable = [
        'name',
        'description',
        'price',
        'price_old',
        'quantity',
        'is_popular',
        'sort',
        'status',
    ];

    protected $casts = [
        'price' => 'float',
        'price_old' => 'float',
        'quantity' => 'int',
        'sort' => 'int',
        'is_popular' => 'boolean'
    ];

    protected $with = ['media', 'categories'];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::addGlobalScope('published', function (Builder $builder) {
            $builder->where('status', EntityStatus::PUBLISHED);
        });
    }

    public function categories()
    {
        return $this->belongsToMany(ProductCategory::class, 'category_product');
    }

    public function registerMediaCollections(): void
    {
        $this
            ->addMediaCollection('default');
    }
}
